DROP SCHEMA IF EXISTS CENTRO_DOCENTE;
CREATE SCHEMA CENTRO_DOCENTE;
USE CENTRO_DOCENTE;

DROP TABLE IF EXISTS PROFESOR;
CREATE TABLE PROFESOR (
	ID_PROFESOR INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DNI CHAR(9) UNIQUE,
	NOMBRE VARCHAR(64),
	EMAIL VARCHAR(64),
	DIRECCION VARCHAR(256),
	TELEFONO CHAR(9),
	SALARIO_EUR DOUBLE
);

DROP TABLE IF EXISTS MODULO;
CREATE TABLE MODULO (
	ID_MODULO INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CODIGO CHAR(4) UNIQUE NOT NULL,
    NOMBRE VARCHAR(64) NOT NULL,
    HORAS_DURACION INT NOT NULL,
    ID_PROFESOR INT UNSIGNED NOT NULL,
    FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESOR (ID_PROFESOR)
	ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS ALUMNO;
CREATE TABLE ALUMNO (
	ID_ALUMNO INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DNI CHAR(9) UNIQUE NOT NULL,
	NOMBRE VARCHAR(64) NOT NULL,
	APELLIDOS VARCHAR(64) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
	TELEFONO CHAR(9)
);

DROP TABLE IF EXISTS ALUMNO_CURSA_MODULO;
CREATE TABLE ALUMNO_CURSA_MODULO (
	ID_ACM INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_ALUMNO INT UNSIGNED NOT NULL,
    ID_MODULO INT UNSIGNED NOT NULL,
    UNIQUE (ID_MODULO, ID_ALUMNO),
    FOREIGN KEY (ID_MODULO) REFERENCES MODULO (ID_MODULO)
	ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNO (ID_ALUMNO)
	ON DELETE CASCADE ON UPDATE CASCADE
);

